apiVersion: apps/v1
kind: Deployment
metadata:
  name: "app-name-here"
  labels:
    app: "app-name-here"
spec:
  template:
  selector:
    matchLabels:
      app: appnamehere
    # quantidade de PODs  
    replicas: 2
    # aqui começa a config dos pods
    template:
      metadata:
        labels:
          app: "app-name-here"
      spec:
        containers:
          - name: appnamehere
            image: "image-app-name-here:latest"
            env:
              # 1. Declarando var env hard-coded
              - name: NAME
                value: "Gustavo"
              # 2. Puxando var env do ConfigMap  
              - name: AGE
                valueFrom:
                  configMapKeyRef:
                    name: appname-env
                    key: AGE
            # 3. Desta forma todas as keys declaradas
            # em configMap são carregadas
            envFrom:
              - configMapKeyRef:
                name: appname-env
                