apiVersion: apps/v1
kind: Deployment
metadata:
  name: "app-name-here"
  labels:
    app: "app-name-here"
spec:
  selector:
    matchLabels:
      app: appnamehere
    # quantidade de PODs  
    replicas: 2
    # aqui começa a config dos pods
    template:
      metadata:
        labels:
          app: "app-name-here"
      spec:
        containers:
          - name: appnamehere
            image: "image-app-name-here:latest"