apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: "app-name-hpa"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: appname
    kind: Deployment
  minReplicas: 1
  maxReplicas: 5
  targetCpuUtilizationPercentage: 25