apiVersion: apps/v1
kind: Secret
metadata:
  name: "appname-secret"
type: Opaque
data:
  # Converter strings para base64 que é o padrão do K8s
  USER: echo "gustavo" | base64  
  PASS: echo "ovatsug" | base64
